### ISSUE TITLE
Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure..

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/codespaces-r#1]
Executing a simple `plot(1:10)`, or any type of R plotting call for that matter, triggers the following error:

```
Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure..
```

(Unfortunately, GitHub isn't letting me upload a screenshot atm.)

@eitsupi I hope you don't mind me tagging you, but do you have any ideas? Is it a port/firewall issue for **httpgd**?

**Comment by eitsupi** [comment]
I ran into this too, but it had nothing to do with R.
In other words, all extensions that show previews, such as Markdown previews, did not work.

I forget the details, but it works by turning off something in the browser's security features.

**Comment by grantmcdermott** [comment]
Thanks @eitsupi, I’ll play around with that.

**Comment by grantmcdermott** [comment]
Solution(s) in this SO thread: https://stackoverflow.com/questions/72498891/github-codespaces-error-loading-webview-error-could-not-register-service-worke
